CREATE TABLE IF NOT EXISTS MPA (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50)
);

CREATE TABLE IF NOT EXISTS FILMS (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(40) NOT NULL,
description varchar(200),
release_date date,
duration integer
);

CREATE TABLE IF NOT EXISTS FILM_MPA (
film_id INTEGER REFERENCES films (id),
mpa_id INTEGER REFERENCES mpa (id),
UNIQUE(film_id, mpa_id)
);

CREATE TABLE IF NOT EXISTS USERS (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(40),
email varchar(40),
login varchar(40),
birthday date
);

CREATE TABLE IF NOT EXISTS FRIENDS (
user_id INTEGER REFERENCES users (id),
friend_id integer,
UNIQUE(user_id, friend_id),
status varchar(15)
);

CREATE TABLE IF NOT EXISTS LIKES (
film_id INTEGER REFERENCES films (id),
user_id INTEGER REFERENCES users (id),
UNIQUE(film_id, user_id)
);

CREATE TABLE IF NOT EXISTS GENRE (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50)
);

CREATE TABLE IF NOT EXISTS GENRES (
film_id INTEGER REFERENCES films (id),
genre_id INTEGER REFERENCES genre (id),
UNIQUE(film_id, genre_id)
);
